CREATE TABLE d01_familia (
d01_cdfamilia BIGSERIAL NOT NULL PRIMARY KEY,
d01_nmfamilia VARCHAR(50));

select * from d01_familia

 insert into d01_familia (d01_nmfamilia) values 
('Acanthaceae'),
('Anacardiaceae'),
('Anisophylleaceae'),
('Annonaceae'),
('Apocynaceae') ,
('Aquifoliaceae') ,
('Araceae') ,
('Araliaceae') ,
('Arecaceae') ,
('Asteraceae') ,
('Avicenniaceae') ,
('Bignoniaceae') ,
('Bixaceae'),
('Bombacaceae'),
('Boraginaceae'),
('Bromeliaceae'),
('Burseraceae'),
('Cactaceae') ,
('Capparaceae'),
('Caricaceae') ,
('Caryocaraceae') ,
('Cecropiaceae') ,
('Celastraceae') ,
('Chrysobalanaceae') ,
('Clethraceae') ,
('Clusiaceae') ,
('Cochlospermaceae'),
('Combretaceae'),
('Connaraceae'),
('Costaceae'),
('Cunoniaceae'),
('Cupressaceae'),
('Cyatheaceae'),
('Cyperaceae'),
('Dialypetalanthaceae'),
('Dichapetalaceae'),
('Dilleniaceae'),
('Duckeodendraceae'),
('Ebenaceae') ,
('Elaeocarpaceae'),
('Ericaceae'),
('Erythroxylaceae'),
('Euphorbiaceae') ,
('Fagaceae') ,
('Flacourtiaceae'),
('Gentianaceae'),
('Heliconiaceae') ,
('Hernandiaceae') ,
('Hippocrateaceae'),
('Hugoniaceae'),
('Humiriaceae'),
('Icacinaceae'),
('Lacistemaceae'),
('Lauraceae'),
('Lecythidaceae'),
('Leguminosae'),
('Leguminosae-caesalpinioideae'),
('Leguminosae-mimosoideae'),
('Leguminosae-papilionoideae'),
('Loganiaceae'),
('Lythraceae'),
('Magnoliaceae') ,
('Malpighiaceae'),
('Malvaceae'),
('Marantaceae'),
('Marcgraviaceae'),
('Melastomataceae'),
('Meliaceae'),
('Mendonciaceae'),
('Menispermaceae'),
('Monimiaceae'),
('Moraceae'),
('Moringaceae'),
('Myristicaceae'),
('Myrsinaceae'),
('Myrtaceae'),
('Nyctaginaceae'),
('Ochnaceae'),
('Olacaceae'),
('Opiliaceae'),
('Passifloraceae'),
('Phytolaccaceae'),
('Pinaceae'),
('Piperaceae'),
('Poaceae'),
('Polygonaceae'),
('Proteaceae'),
('Quiinaceae'),
('Rhabdodendraceae'),
('Rhamnaceae'),
('Rhizophoraceae'),
('Rosaceae'),
('Rubiaceae'),
('Rutaceae'),
('Salicaceae'),
('Sapindaceae'),
('Sapotaceae'),
('Selaginellaceae'),
('Simaroubaceae'),
('Siparunaceae'),
('Smilacaceae'),
('Solanaceae'),
('Sterculiaceae'),
('Styracaceae'),
('Symplocaceae'),
('Tecophilaeaceae'),
('Theaceae'),
('Theophrastaceae'),
('Thymelaeaceae'),
('Tiliaceae'),
('Ulmaceae'),
('Verbenaceae'),
('Violaceae'),
('Vochysiaceae'),
('Ochanaceae'),
('Quinaceae'),
('Curcubitaceae');

select * from d01_familia
